# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hof < Formula
  desc "CUE powered schemas, code gen, data modeling, dag engine, and tui."
  homepage "https://github.com/hofstadter-io/hof"
  version "0.6.9-alpha.6"
  license "Apache-2"

  depends_on "docker"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hofstadter-io/hof/releases/download/v0.6.9-alpha.6/hof_v0.6.9-alpha.6_darwin_amd64"
      sha256 "a9394d0dcd9a95d74c82dba4dd4e76d53e470ff2401756107b4331cc4a166bff"

      def install
        bin.install "hof_v0.6.9-alpha.6_darwin_amd64" => "hof"
        generate_completions_from_executable(bin / "hof", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hofstadter-io/hof/releases/download/v0.6.9-alpha.6/hof_v0.6.9-alpha.6_darwin_arm64"
      sha256 "be0db87e0f49bbd9d52e6793d8abe5a9ab056b65e6acdb71b8f88a94450de9a8"

      def install
        bin.install "hof_v0.6.9-alpha.6_darwin_arm64" => "hof"
        generate_completions_from_executable(bin / "hof", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hofstadter-io/hof/releases/download/v0.6.9-alpha.6/hof_v0.6.9-alpha.6_linux_amd64"
      sha256 "6996554b2cf429752463980479bd191de72e623a361ad3ebc88a8c447e81038b"

      def install
        bin.install "hof_v0.6.9-alpha.6_linux_amd64" => "hof"
        generate_completions_from_executable(bin / "hof", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hofstadter-io/hof/releases/download/v0.6.9-alpha.6/hof_v0.6.9-alpha.6_linux_arm64"
      sha256 "6110cd2e26c954724bfb9f9bc32b3eab076de31d9e834d44f0ad59fe1773a101"

      def install
        bin.install "hof_v0.6.9-alpha.6_linux_arm64" => "hof"
        generate_completions_from_executable(bin / "hof", "completion")
      end
    end
  end
end
