# This file was generated by GoReleaser. DO NOT EDIT.
class Hof < Formula
  desc "Hofstadter Studios CLI"
  homepage "https://github.com/hofstadter-io/hof"
  url "https://github.com/hofstadter-io/hof/releases/download/0.3.0/hof_0.3.0_MacOS-64bit.tar.gz"
  version "0.3.0"
  sha256 "05e65aeaa7481f1da4988951d416c065d95b1f4368fbe19ee51ccc1af0d4f79a"

  def install
    bin.install "hof"
  end
end
