# This file was generated by GoReleaser. DO NOT EDIT.
class Hof < Formula
  desc "Hofstadter Studios CLI"
  homepage "https://github.com/hofstadter-io/hof"
  url "https://github.com/hofstadter-io/hof/releases/download/0.3.1/hof_0.3.1_MacOS-64bit.tar.gz"
  version "0.3.1"
  sha256 "0e45a3ca8c4f5f92e08ea029d042500ffba7c79646ed11eb2fa968046c625bde"

  def install
    bin.install "hof"
  end
end
