# This file was generated by GoReleaser. DO NOT EDIT.
class Hof < Formula
  desc "Hofstadter Studios CLI"
  homepage "https://github.com/hofstadter-io/hof"
  url "https://github.com/hofstadter-io/hof/releases/download/0.3.7/hof_0.3.7_MacOS-64bit.tar.gz"
  version "0.3.7"
  sha256 "70a9cebf504732d21df74fd3771e53029c9f98c5feb9c4df8ab4ef6053f4a847"

  def install
    bin.install "hof"
  end
end
