# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class {{ title .name }} < Formula
  desc "{{ .desc }}"
  homepage "{{ .homepage }}"
  version "{{ .version }}"

  on_macos do
    if Hardware::CPU.intel?
{{ template "build-details" .builds.macos.intel }}
    end
    if Hardware::CPU.arm?
{{ template "build-details"  .builds.macos.arm }}
    end
  end

  on_linux do
    if Hardware::CPU.intel?
{{ template "build-details" .builds.linux.intel }}
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
{{ template "build-details"  .builds.linux.arm }}
    end
  end

  test do
    system "#{bin}/{{ .name }} version"
  end
end

{{ define "build-details" }}
      url "{{ .url }}"
      sha256 "{{ .sha256 }}"

      def install
        bin.install "{{ .name }}"
      end
{{ end }}
